logging:
  level:
    root: INFO

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bank
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        current_session_context_class: thread
        show_sql: true
        format_sql: true
