spring:
  mvc:
    format:
      date: iso
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bank
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
